DROP TABLE IF EXISTS ANSWER;
DROP TABLE IF EXISTS BOX;
DROP TABLE IF EXISTS CARD;
DROP TABLE IF EXISTS QUESTION;
DROP TABLE IF EXISTS STUDY_FILE;
DROP TABLE IF EXISTS TOPIC;
DROP TABLE IF EXISTS TOPIC_CARD;

CREATE TABLE ANSWER (
	ID	INTEGER NOT NULL UNIQUE,
	ANSWER	TEXT,
	PRIMARY KEY(ID AUTOINCREMENT)
);

CREATE TABLE BOX (
    ID INTEGER NOT NULL UNIQUE,
	NAME TEXT,
	PRIMARY KEY(ID)
);

CREATE TABLE CARD (
	ID	INTEGER NOT NULL UNIQUE,
	QUESTION_ID INTEGER NOT NULL,
	ANSWER_ID INTEGER NOT NULL,
	FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(ID),
	FOREIGN KEY (ANSWER_ID) REFERENCES ANSWER(ID),	
	PRIMARY KEY(ID AUTOINCREMENT)
);

CREATE TABLE QUESTION (
	ID	INTEGER NOT NULL UNIQUE,
	QUESTION	TEXT,
	PRIMARY KEY(ID AUTOINCREMENT)
):

CREATE TABLE STUDY_FILE (
	TOPIC_CARD_ID	INTEGER NOT NULL,
	BOX_ID	INTEGER NOT NULL,
	FOREIGN KEY(BOX_ID) REFERENCES BOX(ID),
	FOREIGN KEY(TOPIC_CARD_ID) REFERENCES CARD(ID)
);

CREATE TABLE TOPIC (
    ID INTEGER NOT NULL UNIQUE,
	TOPIC TEXT,
	PRIMARY KEY(ID AUTOINCREMENT)
);

CREATE TABLE TOPIC_CARD (
	ID	INTEGER NOT NULL,
	TOPIC_ID	INTEGER NOT NULL,
	CARD_ID	INTEGER NOT NULL,
	PRIMARY KEY(ID AUTOINCREMENT),
	FOREIGN KEY(TOPIC_ID) REFERENCES TOPIC(ID),
	FOREIGN KEY(CARD_ID) REFERENCES CARD(ID)
);

INSERT INTO BOX(ID,NAME) VALUES (0,"PENDING");
INSERT INTO BOX(ID,NAME) VALUES (1,"BOX 1");
INSERT INTO BOX(ID,NAME) VALUES (2,"BOX 2");
INSERT INTO BOX(ID,NAME) VALUES (3,"BOX 3");
INSERT INTO BOX(ID,NAME) VALUES (4,"BOX 4");
INSERT INTO BOX(ID,NAME) VALUES (5,"BOX 5");
INSERT INTO BOX(ID,NAME) VALUES (6,"LEARNED CARDS");
COMMIT;
